# supabase/config.toml

# Configuração geral do projeto
[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

# Configuração de autenticação
[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

# Configuração do banco de dados local
[db]
port = 54322
major_version = 15

# Configuração de armazenamento (storage)
[storage]
enabled = true
file_size_limit = "50MiB"

# Definições das suas Edge Functions
[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.create-clinic]
verify_jwt = false

[functions.signup-handler]
verify_jwt = false

[functions.create-clinic-with-admin]
verify_jwt = false